# Generated by Django 3.2.7 on 2021-09-26 20:06

import ProductApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstore',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category', to='ProductApp.category'),
        ),
        migrations.AddField(
            model_name='modelstore',
            name='h_img',
            field=models.ImageField(null=True, upload_to=ProductApp.models.img_upload),
        ),
    ]
